Repository sundowndev/phoneinfoga, pull requests merged in 2019-12, with the labels that each got.

#172 Feat: init unit tests
  .github/workflows/main.yml
  tests/lib/banner.py
Labels: enhancement

#171 Feat: implement code formatter and GitHub action
  .github/workflows/main.yml
  .travis.yml
  black.config.toml
  lib/args.py
  lib/banner.py
  lib/colors.py
  lib/format.py
  lib/googlesearch.py
  lib/logger.py
  lib/output.py
  lib/request.py
  scanners/footprints.py
  scanners/localscan.py
  scanners/numverify.py
  scanners/ovh.py
  scanners/recon.py
  tests/lib/banner.py
Labels: enhancement

#174 Init unit tests, refactor CI setup, format files using Black
  .github/workflows/main.yml
  .travis.yml
  black.config.toml
  lib/args.py
  lib/banner.py
  lib/colors.py
  lib/format.py
  lib/googlesearch.py
  lib/logger.py
  lib/output.py
  lib/request.py
  scanners/footprints.py
  scanners/localscan.py
  scanners/numverify.py
  scanners/ovh.py
  scanners/recon.py
  tests/lib/banner.py
Labels: enhancement

#168 added firefox binary path to config
  config.example.py
  docs/googlesearch.md
  lib/googlesearch.py
Labels: enhancement, geckodriver/selenium

#183 Docs: remove references to wget
  docs/install.md
Labels: documentation
